# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-e7662629-130d-43d1-9d7c-49bbe65c07a8";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e7662629-130d-43d1-9d7c-49bbe65c07a8".device = "/dev/disk/by-uuid/e7662629-130d-43d1-9d7c-49bbe65c07a8";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7B60-C62D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/media" =
    { device = "/dev/disk/by-uuid/3fbfaf27-2761-4800-ab97-95fcc9b7a8b1";
      fsType = "btrfs";
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-d350cbe5-5f3e-4b16-96d2-3b4ecc608855"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
