[empty]
path = "./empty"

[catppuccin]
path ="./catppuccin"
aliases = ["ctp"]

[dotnet]
path = "./dotnet"
aliases = ["cs", "csharp"]

[python]
path = "./python"
aliases = ["py"]

[java]
path = "./java"

[rust]
path = "./rust"
aliases = ["rs"]
