# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {

    blacklistedKernelModules = [
      "rtw88_8822bu"
      "rtw88_usb"
      "rtw88_core"
    ];
    kernelModules = [ "kvm-amd" ];

    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usb_storage"
        "usbhid"
        "sd_mod"
      ];
      kernelModules = [ ];
    };

    extraModulePackages = with config.boot.kernelPackages; [
      rtl88x2bu
      # (config.boot.kernelPackages.callPackage ./../../pkgs/rtl88x2bu.nix {})
    ];

    # extraModulePackages = let
    #   rtl88x2bu-git = config.boot.kernelPackages.rtl88x2bu.overrideAttrs (old: {
    #     pname = "rtl88x2bu-git";
    #     version = "unstable-master";
    #     src = pkgs.fetchFromGitHub {
    #       owner = "RinCat";
    #       repo = "RTL88x2BU-Linux-Driver";
    #       rev = "master";
    #       hash = "sha256-P6MnpkWInsOwn9RhPmH7QbGqK7ezJlzp84q7GBoI41g=";
    #     };
    #     meta = old.meta // { broken = false; };
    #   });
    # in [ rtl88x2bu-git ];

    extraModprobeConfig = ''
      options 88x2bu rtw_switch_usb_mode=1
    '';
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/af302a1e-651a-43b6-8fd8-bbae3ea37366";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-dfcf7524-5015-4b57-b358-311a7617feec".device =
    "/dev/disk/by-uuid/dfcf7524-5015-4b57-b358-311a7617feec";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E114-510E";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/mnt/media" = {
    device = "/dev/disk/by-uuid/3fbfaf27-2761-4800-ab97-95fcc9b7a8b1";
    fsType = "btrfs";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/6166f96b-2537-441f-a81f-0dcba2cdd1c1"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp9s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp13s0f3u2.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    amdgpu.initrd.enable = true;
  };
}
