# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-80763acb-1731-4299-9730-a3321e5dae37";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-80763acb-1731-4299-9730-a3321e5dae37".device = "/dev/disk/by-uuid/80763acb-1731-4299-9730-a3321e5dae37";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4D06-BBF8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/media" =
    { device = "/dev/disk/by-uuid/3fbfaf27-2761-4800-ab97-95fcc9b7a8b1";
      fsType = "btrfs";
    };

  fileSystems."/mnt/ssd" =
    { device = "/dev/mapper/luks-9a46aef1-38c3-41d5-b9bd-db8c17e659d1";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-9a46aef1-38c3-41d5-b9bd-db8c17e659d1".device = "/dev/disk/by-uuid/9a46aef1-38c3-41d5-b9bd-db8c17e659d1";

  swapDevices =
    [ { device = "/dev/mapper/luks-f39cc2fd-88f1-4b75-994c-49f9175d4506"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
