{
  inputs,
  pkgs,
  ...
}:

{
  imports = [
    inputs.dms.homeModules.dank-material-shell # .default
    inputs.dms.homeModules.niri
    ./dsearch.nix
    ./plugins.nix
  ];

  # DMS
  programs.dank-material-shell = {
    enable = true;

    # quickshell.package = inputs.quickshell.packages.${pkgs.stdenv.hostPlatform.system}.default;

    systemd = {
      enable = true; # Systemd service for auto-start
      restartIfChanged = true; # Auto-restart dms.service when dankMaterialShell changes
    };

    # Core features
    enableSystemMonitoring = true; # System monitoring widgets (dgop)
    enableVPN = true; # VPN management widget
    enableDynamicTheming = true; # Wallpaper-based theming (matugen)
    enableAudioWavelength = true; # Audio visualizer (cava)
    enableCalendarEvents = true; # Calendar integration (khal)
    
    niri.includes = {
      enable = true;             # Enable config includes hack.
      override = true;           # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
      originalFileName = "hm";   # A new name (without extension) for the config file generated by niri-flake.
      filesToInclude = [         # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
        # "alttab"                 # Please note that niri will throw an error if any of these files are missing.
        # "binds"
        # "colors"
        # "layout"
        "outputs"
        # "wpblur"
      ];
    };
  };
}
