# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-5eef09d9-0753-446e-ae4a-ec54d8037b08";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5eef09d9-0753-446e-ae4a-ec54d8037b08".device = "/dev/disk/by-uuid/5eef09d9-0753-446e-ae4a-ec54d8037b08";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/64EC-F007";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/media" =
    { device = "/dev/mapper/second_disk";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."second_disk".device = "/dev/disk/by-uuid/4b11ffaa-6fd5-446b-920f-4d684e049da5";

  swapDevices =
    [ { device = "/dev/mapper/luks-bee2fb52-34f3-4982-9e1c-42768023be40"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
